apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "postgres-db"
  namespace: "default"
  labels:
    database: "postgres-db"
spec:
  replicas: 1
  selector:
    matchLabels:
      database: "postgres-db"
  template:
    metadata:
      labels:
        database: "postgres-db"
    spec:
      containers:
      - name: "postgres-1"
        image: "postgres:16"
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1Gi
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_USER

        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD

        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_DB
      nodeSelector:
        cloud.google.com/compute-class: "autopilot"
---
apiVersion: "autoscaling/v2"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "postgres-db-hpa-mtok"
  namespace: "default"
  labels:
    database: "postgres-db"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "postgres-db"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      target:
        type: "Utilization"
        averageUtilization: 80
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "postgres-db-service"
  namespace: "default"
  labels:
    database: "postgres-db"
spec:
  ports:
  - protocol: "TCP"
    port: 5432
    targetPort: 5432
  selector:
    database: "postgres-db"
  type: "ClusterIP"