{
 "title": "F1 Telemetry Data",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Session Info",
   "type": "stat",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "http://fastapi_app:8000/session/info",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Fastest Team",
   "type": "stat",
   "gridPos": { "h": 9, "w": 7, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "clocks" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bottomk(1, team_average_lap_time)",
     "legendFormat": "{{team}}"
    }
   ]
  },
  {
   "title": "Driver with Fastest Lap",
   "type": "stat",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "clocks" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "fastest_driver_lap_time", "legendFormat": "{{driver_full}}" }
   ]
  },
  {
   "title": "Team Average Lap Time",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "team_average_lap_time", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Average Lap Time",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "clocks" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg_lap_time", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Race Leaderboard",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "columns": [
      { "selector": "driver_name", "text": "Driver", "type": "string" },
      { "selector": "driver_number", "text": "Driver Number", "type": "string" },
      { "selector": "team_name", "text": "Team", "type": "string" },
      { "selector": "position", "text": "Position", "type": "string" },
      { "selector": "lap_time", "text": "Lap Time", "type": "string" },
      { "selector": "lap_number", "text": "Lap Number", "type": "string" }
     ],
     "parser": "backend",
     "root_selector": "data",
     "source": "url",
     "type": "json",
     "url": "http://fastapi_app:8000/telemetry",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Drivers Championship",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "columns": [
      { "selector": "driver_name", "text": "driver_name", "type": "string" },
      { "selector": "points_current", "text": "points_current", "type": "string" },
      { "selector": "position_current", "text": "position_current", "type": "string" }
     ],
     "parser": "backend",
     "root_selector": "data",
     "source": "url",
     "type": "json",
     "url": "http://fastapi_app:8000/championship/drivers",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Constructors Championship",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "columns": [
      { "selector": "team_name", "text": "team_name", "type": "string" },
      { "selector": "position_current", "text": "position_current", "type": "string" },
      { "selector": "points_current", "text": "points_current", "type": "string" }
     ],
     "parser": "backend",
     "root_selector": "data",
     "source": "url",
     "type": "json",
     "url": "http://fastapi_app:8000/championship/constructors",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  }
 ]
}