{
 "title": "F1 Telemetry System",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "FastAPI Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"fastapi\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Uptime",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"fastapi\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prometheus Metrics Health",
   "type": "stat",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "API Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    { "expr": "sum(rate(requests_total[1m]))", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Failed API Requests",
   "type": "timeseries",
   "description": "Flat lines means it's healthy, and any spikes mean that there are some failed requests",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "increase(failed_api_requests_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Loki Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 14 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=~\".+\"}"
    }
   ]
  },
  {
   "title": "Loki Log Errors & Warnings",
   "type": "logs",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 14 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=~\".+\"} |~ \"level=(warn|error)\""
    }
   ]
  },
  {
   "title": "Data Ingestion Cycle Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "increase(ingestion_cycles_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last Successful Ingestion Time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(last_ingestion_timestamp[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OpenF1 API Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "avg_over_time(openf1_response_time_seconds[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OpenF1 API Tracked Drivers",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "active_drivers", "legendFormat": "__auto" }
   ]
  }
 ]
}