apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: default
data:
  loki.yml: |
    auth_enabled: false

    server:
      http_listen_port: 3100

    common:
      path_prefix: /tmp/loki
      replication_factor: 1
      ring:
        kvstore:
          store: inmemory
      storage:
        filesystem:
          chunks_directory: /tmp/loki/chunks
          rules_directory: /tmp/loki/rules

    schema_config:
      configs:
        - from: 2024-01-01
          store: tsdb
          object_store: filesystem
          schema: v13
          index:
            prefix: index_
            period: 24h

    storage_config:
      filesystem:
        directory: /tmp/loki

    limits_config:
      allow_structured_metadata: false

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki-logs
  namespace: default
  labels:
    monitoring: loki-logs
spec:
  replicas: 1
  selector:
    matchLabels:
      monitoring: loki-logs
  template:
    metadata:
      labels:
        monitoring: loki-logs
    spec:
      containers:
        - name: loki
          image: grafana/loki:3.0.0
          args:
            - "-config.file=/etc/loki/loki.yml"
          ports:
            - containerPort: 3100

          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi

          volumeMounts:
            - name: loki-config
              mountPath: /etc/loki/loki.yml
              subPath: loki.yml

      volumes:
        - name: loki-config
          configMap:
            name: loki-config

      nodeSelector:
        cloud.google.com/compute-class: autopilot

---
apiVersion: v1
kind: Service
metadata:
  name: loki-logs
  namespace: default
spec:
  selector:
    monitoring: loki-logs
  ports:
    - name: http
      port: 3100
      targetPort: 3100
  type: ClusterIP